/* agent icon variables */
export const astraIcon = document.querySelector("#AstraIcon1");
export const breachIcon = document.querySelector("#BreachIcon1");
export const brimstoneIcon = document.querySelector("#BrimstoneIcon1");
export const chamberIcon = document.querySelector("#ChamberIcon1");
export const cypherIcon = document.querySelector("#CypherIcon1");
export const fadeIcon = document.querySelector("#FadeIcon1");
export const gekkoIcon = document.querySelector("#GekkoIcon1");
export const harborIcon = document.querySelector("#HarborIcon1");
export const jettIcon = document.querySelector("#JettIcon1");
export const kayoIcon = document.getElementById("KAYOIcon1");
export const killjoyIcon = document.querySelector("#KilljoyIcon1");
export const neonIcon = document.querySelector("#NeonIcon1");
export const omenIcon = document.querySelector("#OmenIcon1");
export const phoenixIcon = document.querySelector("#PhoenixIcon1");
export const razeIcon = document.querySelector("#RazeIcon1");
export const reynaIcon = document.querySelector("#ReynaIcon1");
export const sageIcon = document.querySelector("#SageIcon1");
export const skyeIcon = document.querySelector("#SkyeIcon1");
export const sovaIcon = document.querySelector("#SovaIcon1");
export const viperIcon = document.querySelector("#ViperIcon1");
export const yoruIcon = document.querySelector("#YoruIcon1");
/* */
